# Generated by Django 4.2 on 2023-04-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gym', '0002_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
