# Generated by Django 4.1.2 on 2023-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gym', '0006_member_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(default='Member_Name', max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
