# Generated by Django 4.1.2 on 2023-05-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gym', '0008_alter_attendance_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
